"""Run Engine control tools."""

from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    import fastmcp


def register(mcp: "fastmcp.FastMCP", get_api) -> None:
    @mcp.tool()
    def re_pause(option: Optional[str] = None, lock_key: Optional[str] = None) -> dict:
        """Pause the currently running plan.

        Parameters
        ----------
        option:
            ``"immediate"`` to pause immediately (may interrupt a data point)
            or ``"deferred"`` to pause at the next checkpoint.  Defaults to
            ``"deferred"``.
        lock_key:
            Lock key required if the environment is locked.
        """
        return get_api().re_pause(option, lock_key=lock_key)

    @mcp.tool()
    def re_resume(lock_key: Optional[str] = None) -> dict:
        """Resume a paused plan.

        Parameters
        ----------
        lock_key:
            Lock key required if the environment is locked.
        """
        return get_api().re_resume(lock_key=lock_key)

    @mcp.tool()
    def re_stop(lock_key: Optional[str] = None) -> dict:
        """Stop the currently running plan at the next checkpoint (clean stop).

        Parameters
        ----------
        lock_key:
            Lock key required if the environment is locked.
        """
        return get_api().re_stop(lock_key=lock_key)

    @mcp.tool()
    def re_abort(lock_key: Optional[str] = None) -> dict:
        """Abort the currently running plan immediately.

        The plan is marked as failed and the Run Engine is returned to the idle state.

        Parameters
        ----------
        lock_key:
            Lock key required if the environment is locked.
        """
        return get_api().re_abort(lock_key=lock_key)

    @mcp.tool()
    def re_halt(lock_key: Optional[str] = None) -> dict:
        """Halt the currently running plan (emergency stop, no cleanup).

        Parameters
        ----------
        lock_key:
            Lock key required if the environment is locked.
        """
        return get_api().re_halt(lock_key=lock_key)

    @mcp.tool()
    def re_runs(option: Optional[str] = None, reload: bool = False) -> dict:
        """Get information about runs generated by the currently running plan.

        Parameters
        ----------
        option:
            ``"open"`` for currently open runs, ``"closed"`` for completed runs,
            or ``None``/``"all"`` for all runs.
        reload:
            Force reload (True) or return cached data (False).
        """
        return get_api().re_runs(option, reload=reload)

    @mcp.tool()
    def kernel_interrupt(
        interrupt_task: Optional[bool] = None,
        interrupt_plan: Optional[bool] = None,
        lock_key: Optional[str] = None,
    ) -> dict:
        """Send a keyboard interrupt to the IPython kernel.

        Only applicable when the RE Manager is configured to use an IPython kernel.

        Parameters
        ----------
        interrupt_task:
            If True, interrupt the currently running foreground task.
        interrupt_plan:
            If True, interrupt the currently running plan.
        lock_key:
            Lock key required if the environment is locked.
        """
        return get_api().kernel_interrupt(
            interrupt_task=interrupt_task,
            interrupt_plan=interrupt_plan,
            lock_key=lock_key,
        )
